name: Playwright Tests
on:
  workflow_call:  # Makes it reusable

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Start Frontend
      run: |
        cd frontend
        npm start & # The '&' makes it run in background
        npx wait-on http://localhost:3000
    - name: Start Frontend
      run: |
        cd tests
    - name: Install dependencies
      run: cd tests && npm ci
    - name: Install Playwright Browsers
      run: cd tests && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd tests && npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 5