# Simple workflow for substituting values to vars
name: Insert API Key

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  replace-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Lambda URL and API Key
        env:
          LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
        run: |
          sed -i "s|LAMBDA_URL_HTML|$LAMBDA_URL|g" frontend/js/funCall.js
          sed -i "s|LAMBDA_API_KEY_HTML|${LAMBDA_API_KEY}|g" frontend/js/funCall.js