name: Frontend Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Replace Lambda URL and API Key
        env:
          LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
        run: |
          sed -i "s|LAMBDA_URL_HTML|$LAMBDA_URL|g" frontend/js/funCall.js
          sed -i "s|LAMBDA_API_KEY_HTML|${LAMBDA_API_KEY}|g" frontend/js/funCall.js
          
      - name: Start Frontend
        run: |
          cd frontend
          npm start & # The '&' makes it run in background
          npx wait-on http://localhost:3000 # Adjust the URL to match your frontend port

  playwright-tests:
    needs: build-and-start
    uses: ./.github/workflows/playwright.yml